<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Dapper"/>
        <PackageReference Include="Npgsql"/>
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions"/>
        <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations"/>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="DocsFlow.Database.Tests"/>
    </ItemGroup>

</Project>
