<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="AWSSDK.S3"/>
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions"/>
        <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations"/>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="DocsFlow.Storage.Tests"/>
    </ItemGroup>

</Project>
